### ISSUE TITLE
Unable to update xml tag attributes with a namespace.

### ISSUE THREAD

**Issue by rspopovi** [sergeyzwezdin/magic-chunks#26] opened 2017-08-11 17:47 UTC
My target xml:

\<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.myapp.name.here" android:installLocation="auto" android:versionCode="10000" android:versionName="1">
	\<uses-sdk android:minSdkVersion="18" android:targetSdkVersion="23" />
	\<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
	\<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	\<application android:label="Scan Plan 2 Test" android:icon="@drawable/scanplanicon" android:theme="@style/MyTheme"></application>
\</manifest>

my Transform code:

{
   "manifest/@android:versionCode" : "10001"
}

Issue:
the colon between 'android' and 'versionCode' is the incorrect syntax, and I cannot infer the correct way, nor can I find documentation that updating attributes with namespaces is even supported. Please help.

**Comment by sergeyzwezdin** [comment] 2017-10-15 10:06
@rspopovi Take a look on this test - https://github.com/sergeyzwezdin/magic-chunks/blob/master/src/MagicChunks.Tests/Documents/XmlDocumentTests.cs#L224-L253

I've added your config and it works ok.

I also noticed that in the sample your XML is malformed. It has unclosed `<application>` tag. The right XML is:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.myapp.name.here" android:installLocation="auto" android:versionCode="10000" android:versionName="1">
<uses-sdk android:minSdkVersion="18" android:targetSdkVersion="23" />
<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<application android:label="Scan Plan 2 Test" android:icon="" android:theme=""/>
</manifest>
```

Closing this issue as it's unable to reproduce. You still having problems let me know.

**Closed by sergeyzwezdin** 2017-10-15 10:06 UTC
Labels: bug

**Comment by sergeyzwezdin** [comment] 2017-12-16 15:20
Latest fixes were released to Nuget and VS Marketplace.
